<?php defined('SYSPATH') or die('No direct script access.');

/**
 * The descriptive data regarding the results of the submitted transaction.
 *
 * @version     3.0
 * @author      Jeremy Dunn
 * @link        http://code.google.com/p/php-fedex-api-wrapper/
 * @package     PHP FedEx API for Kohana
*/
class FedEx_TrackService_Notification
    extends FedEx_AbstractComplexType
{

    /**
     * Identifies the severity of the Notification item. See NotificationSeverityType for list of returned values.
     *
     * @param NotificationSeverityType $Severity
     * return FedEx_TrackService_Notification
     */
    public function setSeverity(FedEx_TrackService_NotificationSeverityType $severity)
    {
        $this->Severity = $severity;
        return $this;
    }
    
    /**
     * Identifies the source - what FedEx system, sub-system, or component generated the Notification item.
     *
     * @param string $Source
     * return FedEx_TrackService_Notification
     */
    public function setSource($source)
    {
        $this->Source = $source;
        return $this;
    }
    
    /**
     * Identifies the error code generated by the FedEx system, sub-system or component.
     *
     * @param string $Code
     * return FedEx_TrackService_Notification
     */
    public function setCode($code)
    {
        $this->Code = $code;
        return $this;
    }
    
    /**
     * Identifies the error message text.
     *
     * @param string $Message
     * return FedEx_TrackService_Notification
     */
    public function setMessage($message)
    {
        $this->Message = $message;
        return $this;
    }
    
    /**
     * Identifies the error message text in the localization requested. Currently not supported.
     *
     * @param string $LocalizedMessage
     * return FedEx_TrackService_Notification
     */
    public function setLocalizedMessage($localizedMessage)
    {
        $this->LocalizedMessage = $localizedMessage;
        return $this;
    }
    
    /**
     * Used internally by FedEx systems for message translation.
     *
     * @param array[NotificationParameter] $MessageParameters
     * return FedEx_TrackService_Notification
     */
    public function setMessageParameters(array $messageParameters)
    {
        $this->MessageParameters = $messageParameters;
        return $this;
    }
    

    
}